### PR TITLE
Alphasign crate

### PR DESCRIPTION
**Pull request by alyxbb**
it crate, It has a bunch of features, most have been tested

### CODE REVIEW

**Comment by ilo-3a29** [comment]
additional notes:
* --fake-serial is gone for now, because you can test that with a port created using `socat` or whatever the windows equivalent of that might be, or just print the things with `println!`
* scripting support is not something that we have reimplemented, following the discussion of it being largely redundant
* I got rid of the pi nix config, if this accidentally got rid of anything nix users need to be able to build this, then these should be re-added.
* everything else is working exactly as it was before moving to the new crate

**Comment by alyxbb** [comment]
everything has had a basic test except:
- chaining multiple commands in a single packet (havent got round to)
- chaining multiple selections in a single packet(cant do)
- toggling speaker using playtone command(spec says do not do with our speaker)
some stuff is left to do:
- finish implementing the store and trigger programmable sound commands. 
- create a message type so text special characters can be dealt with
- work out what allday and never mean for start stop times
- check label is from the set of valid labels
- decode responses and use them
- anything else with a todo

**Comment by ilo-3a29** [comment]
just tested multiple commands in one packet. Works with checksums on, not with checksums off (this is probably something we will try and fix tonight)

**Comment by ilo-3a29** [comment]
sending multiple messages in one packet is now fixed, although split into a different method so it is able to error if you use it with no checksums (which is not supported as it is a pain to implement and not worth it)

**Review by sbaudlr — APPROVED** [review]
Nice! :D I've added the one line needed for us Nix users and made vite serve on 127.0.0.1 so that both that and localhost work :)
The only comment I have is that personally I prefer workspaces where the binaries are also in their own directory but I didn't want to just do that restructure in case people have WIP stuff to commit that would be caused problems by that (also it 100% does not matter and just my opinion).

**Pull request merged**
